
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf' 
      - "./flask-app:/app"
    
  app:
    container_name: app
    build: ./flask-app
    depends_on:
      - es


  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:  
    - discovery.type=single-node





networks:
  default:
    name: foddtracks-net
    external: true
    
    
    


